version: 1.0.{build}
before_build:
- ps: nuget restore
build:
  project: ParseLNK.sln
  verbosity: detailed
environment:
    COVERALLS_REPO_TOKEN:  
       secure: qDtStw7mApnZP+n4GP0BbVQFuDTrskhSuxhobqfRC3Y2GT8aIN29BPm0P/jrOkKh
after_test: 
# generate report for NUnit testing framework:
    - cmd: packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe" -targetargs:"/domain:single Tests\bin\Debug\Tests.exe" -output:coverage.xml
    - cmd: packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml